#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Builds the phporbit developer documentation.
 *
 *     php docs/build.php
 *
 * Writes plain, self-contained HTML into docs/ — no build toolchain, no CDN,
 * no JavaScript required to read a page. Open docs/index.html directly, or
 * point any static server at the folder.
 *
 * PHP samples are highlighted with PHP's own tokeniser rather than a regex
 * approximation, so what you see coloured is what the parser actually sees.
 * The framework's documentation being generated by the language it documents
 * is deliberate.
 *
 * Page sources live in docs/pages/*.php. Each returns an array; the body is a
 * nowdoc of HTML with fenced code blocks:
 *
 *     [[php]] ... [[/php]]      [[bash]] ... [[/bash]]
 *     [[ini]] ... [[/ini]]      [[html]] ... [[/html]]
 *     [[text]] ... [[/text]]
 */

const OUT = __DIR__;

/**
 * Navigation, in reading order. Slugs must match the page files.
 *
 * @var array<string, list<string>>
 */
const NAV = [
    'Start here' => ['index', 'getting-started', 'architecture', 'configuration'],
    'Handling requests' => ['routing', 'controllers', 'requests', 'responses', 'forms'],
    'Building blocks' => ['container', 'middleware', 'templates'],
    'Data' => ['database', 'queries', 'migrations'],
    'Users and safety' => ['security', 'sessions', 'auth', 'validation', 'uploads', 'encryption'],
    'Talking outward' => ['mail'],
    'Operating it' => ['cli', 'admin-ui', 'logging', 'testing', 'deployment'],
];

// ---------------------------------------------------------------- highlighting

/**
 * Reserved words the tokeniser reports as plain T_STRING.
 *
 * @var list<string>
 */
const SOFT_KEYWORDS = [
    'true', 'false', 'null', 'void', 'int', 'string', 'bool', 'float', 'array',
    'self', 'parent', 'mixed', 'never', 'iterable', 'object', 'callable', 'from',
];

function e(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * @return list<int>
 */
function keywordTokens(): array
{
    $names = [
        'T_ABSTRACT', 'T_AS', 'T_BREAK', 'T_CALLABLE', 'T_CASE', 'T_CATCH', 'T_CLASS',
        'T_CLONE', 'T_CONST', 'T_CONTINUE', 'T_DECLARE', 'T_DEFAULT', 'T_DO', 'T_ECHO',
        'T_ELSE', 'T_ELSEIF', 'T_EMPTY', 'T_ENUM', 'T_EXTENDS', 'T_FINAL', 'T_FINALLY',
        'T_FN', 'T_FOR', 'T_FOREACH', 'T_FUNCTION', 'T_GLOBAL', 'T_IF', 'T_IMPLEMENTS',
        'T_INCLUDE', 'T_INSTANCEOF', 'T_INTERFACE', 'T_ISSET', 'T_LIST', 'T_MATCH',
        'T_NAMESPACE', 'T_NEW', 'T_PRINT', 'T_PRIVATE', 'T_PROTECTED', 'T_PUBLIC',
        'T_READONLY', 'T_REQUIRE', 'T_REQUIRE_ONCE', 'T_RETURN', 'T_STATIC', 'T_SWITCH',
        'T_THROW', 'T_TRAIT', 'T_TRY', 'T_UNSET', 'T_USE', 'T_VAR', 'T_WHILE', 'T_YIELD',
        'T_LOGICAL_AND', 'T_LOGICAL_OR', 'T_LOGICAL_XOR', 'T_ENDIF', 'T_ENDFOREACH',
    ];

    $ids = [];
    foreach ($names as $name) {
        if (defined($name)) {
            /** @var int $id */
            $id = constant($name);
            $ids[] = $id;
        }
    }

    return $ids;
}

function highlightPhp(string $code): string
{
    $keywords = keywordTokens();
    $tokens = token_get_all("<?php\n" . $code);
    array_shift($tokens);

    $count = count($tokens);
    $out = '';

    foreach ($tokens as $index => $token) {
        if (is_string($token)) {
            $out .= '<span class="tk-p">' . e($token) . '</span>';

            continue;
        }

        [$id, $text] = $token;
        $class = null;

        if ($id === T_COMMENT || $id === T_DOC_COMMENT) {
            $class = 'tk-comment';
        } elseif ($id === T_CONSTANT_ENCAPSED_STRING || $id === T_ENCAPSED_AND_WHITESPACE) {
            $class = 'tk-string';
        } elseif ($id === T_VARIABLE) {
            $class = 'tk-var';
        } elseif ($id === T_LNUMBER || $id === T_DNUMBER) {
            $class = 'tk-num';
        } elseif (in_array($id, $keywords, true)) {
            $class = 'tk-keyword';
        } elseif (defined('T_NAME_QUALIFIED') && ($id === T_NAME_QUALIFIED || $id === T_NAME_FULLY_QUALIFIED)) {
            $class = 'tk-class';
        } elseif ($id === T_STRING) {
            if (in_array(strtolower($text), SOFT_KEYWORDS, true)) {
                $class = 'tk-keyword';
            } elseif (nextSignificant($tokens, $index, $count) === '(') {
                $class = 'tk-fn';
            } elseif ($text !== '' && ctype_upper($text[0])) {
                $class = 'tk-class';
            }
        }

        $out .= $class === null ? e($text) : '<span class="' . $class . '">' . e($text) . '</span>';
    }

    return $out;
}

/**
 * @param list<array{0: int, 1: string, 2: int}|string> $tokens
 */
function nextSignificant(array $tokens, int $index, int $count): ?string
{
    for ($i = $index + 1; $i < $count; $i++) {
        $token = $tokens[$i];

        if (is_array($token) && $token[0] === T_WHITESPACE) {
            continue;
        }

        return is_string($token) ? $token : $token[1];
    }

    return null;
}

/**
 * Shell samples: comments and the prompt get their own colour, nothing else.
 */
function highlightShell(string $code): string
{
    $lines = [];

    foreach (explode("\n", $code) as $line) {
        if (preg_match('/^(\s*)(#.*)$/', $line, $m) === 1) {
            $lines[] = e($m[1]) . '<span class="tk-comment">' . e($m[2]) . '</span>';

            continue;
        }

        $lines[] = preg_replace(
            '/^(\s*)(\$ )/',
            '$1<span class="tk-p">$ </span>',
            e($line),
        ) ?? e($line);
    }

    return implode("\n", $lines);
}

function highlightIni(string $code): string
{
    $lines = [];

    foreach (explode("\n", $code) as $line) {
        if (preg_match('/^(\s*)(#.*)$/', $line, $m) === 1) {
            $lines[] = e($m[1]) . '<span class="tk-comment">' . e($m[2]) . '</span>';
        } elseif (preg_match('/^([A-Z0-9_]+)(=)(.*)$/', $line, $m) === 1) {
            $lines[] = '<span class="tk-var">' . e($m[1]) . '</span>'
                . '<span class="tk-p">=</span>'
                . '<span class="tk-string">' . e($m[3]) . '</span>';
        } else {
            $lines[] = e($line);
        }
    }

    return implode("\n", $lines);
}

/**
 * Replaces [[lang]] … [[/lang]] fences with highlighted code blocks.
 */
function renderFences(string $body): string
{
    return (string) preg_replace_callback(
        '/\[\[(php|bash|ini|html|text)\]\]\n?(.*?)\n?\[\[\/\1\]\]/s',
        static function (array $match): string {
            $lang = $match[1];
            $code = rtrim($match[2]);

            $rendered = match ($lang) {
                'php' => highlightPhp($code),
                'bash' => highlightShell($code),
                'ini' => highlightIni($code),
                default => e($code),
            };

            $label = match ($lang) {
                'php' => 'PHP',
                'bash' => 'Shell',
                'ini' => '.env',
                'html' => 'Template',
                default => 'Output',
            };

            return '<figure class="code"><figcaption>' . $label . '</figcaption>'
                . '<pre><code>' . $rendered . '</code></pre></figure>';
        },
        $body,
    );
}

// -------------------------------------------------------------------- layout

/**
 * @param array{slug: string, title: string, nav?: string, summary: string, body: string} $page
 * @param array<string, array{title: string, nav: string, summary: string}> $meta
 */
function layout(array $page, array $meta): string
{
    $slug = $page['slug'];
    $nav = '';

    foreach (NAV as $group => $slugs) {
        $nav .= '<p class="nav-group">' . e($group) . '</p><ul>';

        foreach ($slugs as $item) {
            $current = $item === $slug ? ' class="current" aria-current="page"' : '';
            $nav .= '<li><a href="' . e($item) . '.html"' . $current . '>'
                . e($meta[$item]['nav']) . '</a></li>';
        }

        $nav .= '</ul>';
    }

    // Previous / next across the whole flattened order.
    $order = array_merge(...array_values(NAV));
    $position = array_search($slug, $order, true);
    $pager = '';

    if ($position !== false) {
        $previous = $position > 0 ? $order[$position - 1] : null;
        $next = $order[$position + 1] ?? null;

        $pager = '<nav class="pager">';
        $pager .= $previous === null ? '<span></span>'
            : '<a href="' . e($previous) . '.html"><span>Previous</span>' . e($meta[$previous]['title']) . '</a>';
        $pager .= $next === null ? '<span></span>'
            : '<a class="next" href="' . e($next) . '.html"><span>Next</span>' . e($meta[$next]['title']) . '</a>';
        $pager .= '</nav>';
    }

    $body = renderFences($page['body']);
    $title = e($page['title']);

    return <<<HTML
        <!doctype html>
        <html lang="en">
        <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{$title} — phporbit</title>
        <meta name="description" content="{$page['summary']}">
        <link rel="icon" href="assets/favicon.svg" type="image/svg+xml">
        <link rel="stylesheet" href="assets/docs.css">
        </head>
        <body>
        <a class="skip" href="#content">Skip to content</a>

        <div class="shell">
        <aside class="sidebar">
            <a class="brand" href="index.html">
                <picture>
                    <source srcset="assets/logo-on-dark.svg" media="(prefers-color-scheme: dark)">
                    <img src="assets/logo-on-light.svg" alt="phporbit" width="112" height="32">
                </picture>
            </a>
            <p class="tagline">Developer documentation</p>
            <nav aria-label="Documentation">{$nav}</nav>
        </aside>

        <main id="content">
            <article>
                <h1>{$title}</h1>
                <p class="summary">{$page['summary']}</p>
                {$body}
            </article>
            {$pager}
            <footer class="site-footer">
                <p>phporbit documentation · generated by <code>php docs/build.php</code></p>
            </footer>
        </main>
        </div>
        </body>
        </html>
        HTML;
}

// ---------------------------------------------------------------------- build

$pages = [];

foreach (glob(__DIR__ . '/pages/*.php') ?: [] as $file) {
    /** @var array{slug: string, title: string, nav?: string, summary: string, body: string} $page */
    $page = require $file;
    $pages[$page['slug']] = $page;
}

$meta = [];
foreach ($pages as $slug => $page) {
    $meta[$slug] = [
        'title' => $page['title'],
        // A page may use a shorter label in the sidebar than as its heading.
        'nav' => $page['nav'] ?? $page['title'],
        'summary' => $page['summary'],
    ];
}

// Every slug in the navigation must exist, or a reader hits a dead link.
$missing = [];
foreach (NAV as $slugs) {
    foreach ($slugs as $slug) {
        if (!isset($pages[$slug])) {
            $missing[] = $slug;
        }
    }
}

if ($missing !== []) {
    fwrite(STDERR, 'Navigation refers to missing pages: ' . implode(', ', $missing) . PHP_EOL);
    exit(1);
}

@mkdir(OUT . '/assets', 0o755, true);

// The docs carry their own copies of the brand assets so the folder can be
// moved or served on its own.
foreach ([
    __DIR__ . '/../public/favicon.svg' => OUT . '/assets/favicon.svg',
    // Both variants: the wordmark is a fixed colour, so the page picks the one
    // that contrasts with the reader's theme.
    __DIR__ . '/../brand/phporbit-logo-on-dark.svg' => OUT . '/assets/logo-on-dark.svg',
    __DIR__ . '/../brand/phporbit-logo-on-light.svg' => OUT . '/assets/logo-on-light.svg',
] as $from => $to) {
    if (is_file($from)) {
        copy($from, $to);
    }
}

foreach ($pages as $slug => $page) {
    file_put_contents(OUT . '/' . $slug . '.html', layout($page, $meta));
}

printf("built %d pages into %s\n", count($pages), OUT);
